context_giver_task:
  description: >
    Understand what Ovan wants to learn based on {topic}, 
    and create a curriculum plan or roadmap consisting of 
    materials and data that support Ovan's learning.
    Ensure that you create a curriculum relevant to {topic} 
    and of high quality to guide Ovan's learning materials.
  expected_output: >
    List number, which is the sequence of materials 
    that Ovan must study based on {topic}, with detailed bulleted 
    lists containing data that supports each material in the list number.
  agent: context_giver_guy

# research_task:
#   description: >
# 
#   expected_output: >

#   agent: researcher_guy

# adjust_task:
#   description: >
# 
#   expected_output: >

#   agent: adjuster_guy