main_task:
  description: >
    Pahami apa yang ingin dipelajari Ovan mengenai {topic},
    dan buat roadmap kurikulum untuk memandu asisten Peneliti Ovan,
    Yang terdiri dari materi dan data yang mendukung pembelajaran Ovan.
    Pastikan Anda membuat kurikulum berkualitas tinggi dan relevan tentang {topic} untuk
    membimbing asisten Peneliti Ovan dalam menemukan materi pembelajaran terkait.
  expected_output: >
    Kurikulum dalam bentuk numbered list,yang merupakan urutan materi yang harus dicari oleh asisten peneliti Ovan berdasarkan {topic}, 
    dengan daftar poin-poin terperinci yang berisi data yang mendukung setiap item dalam nomor daftar.
    Pastikan tidak ada teks pengantar atau penjelasan tambahan dari Anda.
    Cukup berikan serangkaian kurikulum sebagai panduan bagi asisten peneliti Ovan.
